version: "3.7"

services: 
  stats-display:
    image: stats-display
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_web
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.stats-display.rule=Host(`stats.homelab`)"
      - "traefik.http.services.stats-display.loadbalancer.server.port=42069"

networks:
  traefik_web:
    external: true